# Window Rules

windowrule=isfloating:1,appid:launcher
windowrule=isnoborder:0,appid:launcher
windowrule=animation_type_open:slide,appid:launcher
windowrule=animation_type_close:zoom,appid:launcher

windowrule=isfloating:1,isoverlay:1,isnoborder:1,isunglobal:1,width:400,height:400,offsetx:9999,offsety:9999,appid:steam_app_3419430,title:BongoCat

windowrule=unfocused_opacity:0.6,focused_opacity:0.9,appid:^kitty$

# Set default layout to scroller
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

